spring:
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    output:
        ansi:
            enabled: always
    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/default_db}
        username: ${DB_USER:root}
        password: ${DB_PASSWORD:password}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 5
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 9090
