name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  call-build:
    uses: ./.github/workflows/develop-build.yml

  deploy:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: guitar-eik-app
          path: .

      - name: List all files to find the JAR
        run: ls -R

      - name: Upload JAR to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER}}
          password: ${{ secrets.PASSWORD}}
          source: "target/*.jar"
          target: "/root/guitar-eik/deploy"
          strip_components: 1

      - name: Restart Spring Boot App on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER}}
          password: ${{ secrets.PASSWORD}}
          script: |
            mkdir -p /root/guitar-eik/deploy
            cd /root/guitar-eik/deploy
            fuser -k 9090/tcp || true

            mv server-4.0.5.jar app.jar

            export DB_URL="${{ secrets.DB_URL }}"
            export DB_USER="${{ secrets.DB_USER }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"

            nohup java -jar app.jar > app.log 2>&1 &
