name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  call-build:
    uses: ./.github/workflows/develop-build.yml

  deploy:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: guitar-eik-app
          path: .

      - name: List all files to find the JAR
        run: ls -R

      - name: Upload JAR to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER}}
          password: ${{ secrets.PASSWORD}}
          source: "server-4.0.5.jar"
          target: "/root/guitar-eik/deploy"
          strip_components: 1

      - name: Restart Spring Boot App on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER}}
          password: ${{ secrets.PASSWORD}}
          script: |
            cd /root/guitar-eik/deploy

            PID=$(lsof -t -i:9090)
            if [ ! -z "$PID" ]; then
              kill -9 $PID
              echo "Process killed."
            fi

            echo "Waiting for port 9090 to be free..."
            while lsof -Pi :9090 -sTCP:LISTEN -t >/dev/null ; do
                sleep 1
            done
            echo "Port 9090 is free."

            export DB_URL="${{ secrets.DB_URL }}"
            export DB_USER="${{ secrets.DB_USER }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"

            nohup java -jar server-4.0.5.jar > app.log 2>&1 &
            echo "App started successfully."
