name: Testing Develop Branch

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set uo JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Build and Test with Maven Fix
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        run: |
          mvn clean package --file pom.xml \
          -Dspring.datasource.url=$DB_URL \
          -Dspring.datasource.username=$DB_USER \
          -Dspring.datasource.password=$DB_PASSWORD

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: guitar-eik-app
          path: target/*.jar

      - name: Check target folder content
        run: ls -la target/
